apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-your-company-com
  namespace: cert-manager
spec:
  secretName: test-your-company-com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: test.yourcompany.com
  dnsNames:
  - test.youcompany.com